// Team A — wireframe single source. CS 356 Project 1, November 2026.
// One record per information block (one skill). Every page in this
// prototype is rendered by selecting on these attributes; no skill is
// written into the HTML anywhere.
//
// name and url are verbatim from the live site's assets/lang/eng/skills-data.js.
// category, group and moment are ours, from the card sort (Report A).
window.WIREFRAME_DATA = {
  builtFor: "CS 356 Project 1 — wireframe turn-in (Team A)",
  source: "53-skill inventory, Teacher Development Skills manual",

  // L1 of the category view. Five categories, no Spirit category — see
  // the report: one sort in eight made one, so we did not force it.
  categories: [
    { slug: "talk", name: "Getting people to talk" },
    { slug: "love", name: "Knowing and loving the people you teach" },
    { slug: "christ", name: "Teaching about Jesus Christ" },
    { slug: "prep", name: "Getting ready before Sunday" },
    { slug: "attention", name: "Keeping their attention" }
  ],

  // L2 of the category view. Group labels use only words participants said.
  groups: [
    { slug: "not-answering-it-yourself", category: "Getting people to talk", name: "Not answering it yourself" },
    { slug: "asking-for-a-real-answer", category: "Getting people to talk", name: "Asking so you get a real answer" },
    { slug: "talking-to-each-other", category: "Getting people to talk", name: "Getting them talking to each other" },
    { slug: "getting-to-know-them", category: "Knowing and loving the people you teach", name: "Getting to know them" },
    { slug: "during-the-week", category: "Knowing and loving the people you teach", name: "Caring about them during the week" },
    { slug: "safe-to-speak-up", category: "Knowing and loving the people you teach", name: "Making the room safe to speak up" },
    { slug: "about-their-own-life", category: "Teaching about Jesus Christ", name: "Making it about their own life" },
    { slug: "finding-him-in-the-scriptures", category: "Teaching about Jesus Christ", name: "Finding Him in the scriptures" },
    { slug: "bearing-witness-in-class", category: "Teaching about Jesus Christ", name: "Bearing witness in class" },
    { slug: "what-the-prophets-say", category: "Teaching about Jesus Christ", name: "What the prophets say" },
    { slug: "getting-yourself-ready", category: "Getting ready before Sunday", name: "Getting yourself ready" },
    { slug: "planning-the-lesson", category: "Getting ready before Sunday", name: "Planning the lesson" },
    { slug: "invitations-they-take-home", category: "Getting ready before Sunday", name: "Invitations they take home" },
    { slug: "see-or-hear", category: "Keeping their attention", name: "Something they can see or hear" },
    { slug: "do-not-watch", category: "Keeping their attention", name: "Something they do, not watch" }
  ],

  // The second view. Not a sixth category — an attribute every block carries.
  moments: [
    { key: "opening", name: "The first few minutes", blurb: "You are starting the lesson." },
    { key: "during", name: "In the middle of the lesson", blurb: "You are in the thick of it." },
    { key: "closing", name: "The last few minutes", blurb: "You are landing it and sending them out." },
    { key: "after", name: "After class and during the week", blurb: "Sunday is over, or next Sunday is coming." }
  ],

  // The 53 information blocks.
  skills: [
    { id: "004.title_number1",
      name: "Help students connect what they are learning with how Christ exemplifies the principle.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/004-emphasize-the-example-of-jesus-christ?lang=eng#title_number1",
      category: "Teaching about Jesus Christ",
      group: "Making it about their own life",
      moment: ["during"] },
    { id: "004.title_number2",
      name: "Use pictures and videos of Jesus Christ to illustrate a gospel principle.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/004-emphasize-the-example-of-jesus-christ?lang=eng#title_number2",
      category: "Keeping their attention",
      group: "Something they can see or hear",
      moment: ["opening", "during"] },
    { id: "005.p16",
      name: "Create search questions to help students identify roles, titles, symbols, attributes, and characteristics of Jesus Christ.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/005-teach-about-titles-roles-attributes?lang=eng#p16",
      category: "Teaching about Jesus Christ",
      group: "Finding Him in the scriptures",
      moment: ["during"] },
    { id: "005.title_number17",
      name: "Ask questions that allow students to identify roles Jesus Christ can have in their lives.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/005-teach-about-titles-roles-attributes?lang=eng#title_number17",
      category: "Teaching about Jesus Christ",
      group: "Finding Him in the scriptures",
      moment: ["during"] },
    { id: "006.title_number1",
      name: "Ask questions that help students learn about Jesus Christ through symbols in the scriptures.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/006-look-for-symbols-that-testify-of-christ?lang=eng#title_number1",
      category: "Teaching about Jesus Christ",
      group: "Finding Him in the scriptures",
      moment: ["during"] },
    { id: "006.title_number2",
      name: "Help students have a sensory experience with scriptural objects that symbolize Jesus Christ.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/03-teach-about-jesus-christ/006-look-for-symbols-that-testify-of-christ?lang=eng#title_number2",
      category: "Keeping their attention",
      group: "Something they do, not watch",
      moment: ["during"] },
    { id: "007.title_number1",
      name: "Ask questions that focus on connecting the Lord’s power, mercy, and influence to the truths being taught.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/007-help-learners-recognize-love-power-mercy?lang=eng#title_number1",
      category: "Teaching about Jesus Christ",
      group: "Bearing witness in class",
      moment: ["during"] },
    { id: "007.title_number2",
      name: "Give invitations that help learners recognize the Lord’s love, power, and mercy in their own experiences.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/007-help-learners-recognize-love-power-mercy?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "Making it about their own life",
      moment: ["closing"] },
    { id: "008.title_number1",
      name: "Statements that help students know and feel the love of Heavenly Father and Jesus Christ.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/008-help-learners-strengthen-relationship-with-heavenly-father?lang=eng#title_number1",
      category: "Teaching about Jesus Christ",
      group: "Bearing witness in class",
      moment: ["during", "closing"] },
    { id: "008.title_number2",
      name: "Ask questions that help students find examples of Heavenly Father’s love in the scripture passage.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/008-help-learners-strengthen-relationship-with-heavenly-father?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "Finding Him in the scriptures",
      moment: ["during"] },
    { id: "009.title_number1",
      name: "Observe Christlike attributes in students and share what you’ve noticed in ways that inspire them to continue to be like Him.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/009-help-learners-strive-to-be-more-like-jesus-christ?lang=eng#title_number1",
      category: "Knowing and loving the people you teach",
      group: "Making the room safe to speak up",
      moment: ["during", "after"] },
    { id: "009.title_number2",
      name: "Invite students to look for ways to follow the example of Jesus Christ in their personal lives.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/04-help-learners-come-unto-jesus-christ/009-help-learners-strive-to-be-more-like-jesus-christ?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "Making it about their own life",
      moment: ["closing"] },
    { id: "011.title_number1",
      name: "Study recent prophetic messages to understand how Heavenly Father sees young people.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/011-see-learners-the-way-god-sees?lang=eng#title_number1",
      category: "Knowing and loving the people you teach",
      group: "Getting to know them",
      moment: ["after"] },
    { id: "011.title_number2",
      name: "“Think celestial” about your students to help you see them as God does.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/011-see-learners-the-way-god-sees?lang=eng#title_number2",
      category: "Knowing and loving the people you teach",
      group: "Getting to know them",
      moment: ["opening", "after"] },
    { id: "012.intro2",
      name: "Observe and ask about students’ interests.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/012-seek-to-know-them?lang=eng#intro2",
      category: "Knowing and loving the people you teach",
      group: "Getting to know them",
      moment: ["opening", "after"] },
    { id: "012.title_number4",
      name: "Pause, reflect, and answer questions we ask ourselves that invite a Christlike spirit of discernment, love, and empathy in our interactions.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/012-seek-to-know-them?lang=eng#title_number4",
      category: "Knowing and loving the people you teach",
      group: "Caring about them during the week",
      moment: ["during", "after"] },
    { id: "012.title_number3",
      name: "Seek to clarify and understand the real intent of students’ questions, feelings, and beliefs.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/012-seek-to-know-them?lang=eng#title_number3",
      category: "Knowing and loving the people you teach",
      group: "Getting to know them",
      moment: ["during"] },
    { id: "013.intro2",
      name: "Pray and ask how you can help your students and follow the promptings from the Holy Ghost.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/013-pray-for-them-by-name?lang=eng#intro2",
      category: "Knowing and loving the people you teach",
      group: "Caring about them during the week",
      moment: ["after"] },
    { id: "013.intro3",
      name: "Invite students to pray for other students.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/013-pray-for-them-by-name?lang=eng#intro3",
      category: "Knowing and loving the people you teach",
      group: "Making the room safe to speak up",
      moment: ["opening", "closing"] },
    { id: "014.intro2",
      name: "Communicate that you value students before they comment or as they raise their hand to comment.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/014-create-a-safe-environment?lang=eng#intro2",
      category: "Knowing and loving the people you teach",
      group: "Making the room safe to speak up",
      moment: ["during"] },
    { id: "014.title_number3",
      name: "Communicate that students are not only welcome but needed.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/014-create-a-safe-environment?lang=eng#title_number3",
      category: "Knowing and loving the people you teach",
      group: "Making the room safe to speak up",
      moment: ["opening", "during"] },
    { id: "015.title_number1",
      name: "Send a message to a student’s parent about something positive you have noticed about their child.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/015-find-appropriate-ways-to-express-love?lang=eng#title_number1",
      category: "Knowing and loving the people you teach",
      group: "Caring about them during the week",
      moment: ["after"] },
    { id: "015.title_number2",
      name: "Testify of God’s love when it is hard for you to feel or express love to those you teach.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/05-love-those-you-teach/015-find-appropriate-ways-to-express-love?lang=eng#title_number2",
      category: "Knowing and loving the people you teach",
      group: "Caring about them during the week",
      moment: ["during"] },
    { id: "017.title_number1",
      name: "Use the document “Improving as a Christlike Teacher—A Personal Evaluation” to invite the Holy Ghost to help you refine your preparations to teach.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/017-prepare-yourself-spiritually?lang=eng#title_number1",
      category: "Getting ready before Sunday",
      group: "Getting yourself ready",
      moment: ["after"] },
    { id: "017.title_number2",
      name: "Ask questions to assess your own experience and testimony with Jesus Christ and the doctrine and principles in the lesson.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/017-prepare-yourself-spiritually?lang=eng#title_number2",
      category: "Getting ready before Sunday",
      group: "Getting yourself ready",
      moment: ["after"] },
    { id: "018.title_number1",
      name: "Ask a question to assess learning before moving on in the lesson.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/018-always-be-ready-to-respond-to-spiritual-promptings?lang=eng#title_number1",
      category: "Getting people to talk",
      group: "Not answering it yourself",
      moment: ["during"] },
    { id: "018.title_number2",
      name: "Listen to and observe students to ask follow-up questions.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/018-always-be-ready-to-respond-to-spiritual-promptings?lang=eng#title_number2",
      category: "Getting people to talk",
      group: "Not answering it yourself",
      moment: ["during"] },
    { id: "019.intro1",
      name: "Create student self-evaluations about a doctrine, truth, or principle.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/019-create-settings-and-opportunities-to-be-taught-by-holy-ghost?lang=eng#intro1",
      category: "Getting ready before Sunday",
      group: "Planning the lesson",
      moment: ["during", "after"] },
    { id: "019.title_number2",
      name: "Use sacred music. Invite students to identify lines and phrases in sacred music that connect with the truths they are learning.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/019-create-settings-and-opportunities-to-be-taught-by-holy-ghost?lang=eng#title_number2",
      category: "Keeping their attention",
      group: "Something they can see or hear",
      moment: ["opening", "during"] },
    { id: "020.intro2",
      name: "Before responding to a student’s question or comment, pause and think, “What can I ask them?” or “What can I invite them to do?”",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/020-help-learners-seek-recognize-act-on-personal-revelation?lang=eng#intro2",
      category: "Getting people to talk",
      group: "Not answering it yourself",
      moment: ["during"] },
    { id: "020.title_number3",
      name: "Share statements that help students recognize when the Holy Ghost is performing His role or function.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/020-help-learners-seek-recognize-act-on-personal-revelation?lang=eng#title_number3",
      category: "Teaching about Jesus Christ",
      group: "Bearing witness in class",
      moment: ["during"] },
    { id: "021.title_number1",
      name: "Create prompts that help students verbalize their feelings, experiences, and testimony.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/021-bear-testimony-often?lang=eng#title_number1",
      category: "Getting people to talk",
      group: "Getting them talking to each other",
      moment: ["during", "closing"] },
    { id: "021.title_number2",
      name: "Testify more frequently and more powerfully of Jesus Christ.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/06-teach-by-the-spirit/021-bear-testimony-often?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "Bearing witness in class",
      moment: ["during", "closing"] },
    { id: "023.title_number1",
      name: "Create open-ended search questions that help learners discover gospel doctrine and principles for themselves and do not lead students to a specific response.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/023-learn-the-doctrine-of-jesus-christ?lang=eng#title_number1",
      category: "Getting people to talk",
      group: "Asking so you get a real answer",
      moment: ["during"] },
    { id: "023.title_number2",
      name: "Search the scriptures and words of the prophets for deeper understanding.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/023-learn-the-doctrine-of-jesus-christ?lang=eng#title_number2",
      category: "Getting ready before Sunday",
      group: "Getting yourself ready",
      moment: ["after"] },
    { id: "024.title_number1",
      name: "Prepare invitations that help students connect truths found in the scriptures to what living prophets are saying.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/024-teach-from-scriptures?lang=eng#title_number1",
      category: "Teaching about Jesus Christ",
      group: "What the prophets say",
      moment: ["during"] },
    { id: "024.title_number2",
      name: "Express your love for and testimony of prophets as their words are shared in class.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/024-teach-from-scriptures?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "What the prophets say",
      moment: ["during"] },
    { id: "025.intro2",
      name: "Create student self-evaluations that help them recognize their current understanding and abilities about scripture study skills.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/025-help-learners-seek-recognize-understand-truths?lang=eng#intro2",
      category: "Getting ready before Sunday",
      group: "Planning the lesson",
      moment: ["during", "after"] },
    { id: "025.title_number3",
      name: "Consider assessment questions to carefully choose media, personal stories, and object lessons.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/025-help-learners-seek-recognize-understand-truths?lang=eng#title_number3",
      category: "Getting ready before Sunday",
      group: "Planning the lesson",
      moment: ["after"] },
    { id: "026.intro2",
      name: "Ask questions that help students identify and state converting principles.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/026-focus-on-truths-that-lead-to-conversion?lang=eng#intro2",
      category: "Getting people to talk",
      group: "Asking so you get a real answer",
      moment: ["during"] },
    { id: "026.title_number3",
      name: "Respond to questions in a way that avoids speculation and nondoctrinal personal ideas.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/026-focus-on-truths-that-lead-to-conversion?lang=eng#title_number3",
      category: "Getting people to talk",
      group: "Asking so you get a real answer",
      moment: ["during"] },
    { id: "027.title_number1",
      name: "Prepare invitations and prompts that help students find personal relevance to a scripture block.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/027-help-learners-find-personal-relevance?lang=eng#title_number1",
      category: "Getting ready before Sunday",
      group: "Planning the lesson",
      moment: ["during", "after"] },
    { id: "027.title_number2",
      name: "Start a learning activity by inviting students to ponder a personal circumstance.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/07-teach-the-doctrine/027-help-learners-find-personal-relevance?lang=eng#title_number2",
      category: "Keeping their attention",
      group: "Something they do, not watch",
      moment: ["opening"] },
    { id: "029.title_number1",
      name: "Resist the tendency to respond to every comment and question and invite the class to respond.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/029-help-learners-take-responsibility?lang=eng#title_number1",
      category: "Getting people to talk",
      group: "Not answering it yourself",
      moment: ["during"] },
    { id: "029.title_number2",
      name: "Focus on what the learner can do in class that the teacher typically does.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/029-help-learners-take-responsibility?lang=eng#title_number2",
      category: "Getting people to talk",
      group: "Not answering it yourself",
      moment: ["during"] },
    { id: "030.intro2",
      name: "Assist students in creating a daily scripture study goal.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/030-encourage-learners-to-know-the-savior?lang=eng#intro2",
      category: "Getting ready before Sunday",
      group: "Invitations they take home",
      moment: ["closing", "after"] },
    { id: "030.title_number3",
      name: "Develop and ask questions that help learners connect what they have learned in their personal and family scripture study to the classroom experience.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/030-encourage-learners-to-know-the-savior?lang=eng#title_number3",
      category: "Getting people to talk",
      group: "Asking so you get a real answer",
      moment: ["opening", "during"] },
    { id: "031.title_number1",
      name: "Create invitations that help learners prepare for the next learning experience.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/031-invite-learners-to-prepare?lang=eng#title_number1",
      category: "Getting ready before Sunday",
      group: "Invitations they take home",
      moment: ["closing", "after"] },
    { id: "031.title_number2",
      name: "Create a meaningful invitation connected to the lesson outcome to be used at the beginning of each lesson.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/031-invite-learners-to-prepare?lang=eng#title_number2",
      category: "Getting ready before Sunday",
      group: "Planning the lesson",
      moment: ["opening"] },
    { id: "032.intro2",
      name: "Help students create or begin gospel conversations.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/032-encourage-learners-to-share-truths?lang=eng#intro2",
      category: "Getting people to talk",
      group: "Getting them talking to each other",
      moment: ["during", "after"] },
    { id: "032.title_number3",
      name: "Prepare invitations for students to share with each other what they are learning.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/032-encourage-learners-to-share-truths?lang=eng#title_number3",
      category: "Getting people to talk",
      group: "Getting them talking to each other",
      moment: ["during"] },
    { id: "033.title_number1",
      name: "Plan to follow up on invitations given in a previous class and invite learners to share their experiences living what they learned.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/033-invite-learners-to-live?lang=eng#title_number1",
      category: "Getting ready before Sunday",
      group: "Invitations they take home",
      moment: ["opening", "after"] },
    { id: "033.title_number2",
      name: "Ask search questions that help learners consider who God is and blessings He offers them.",
      url: "https://www.churchofjesuschrist.org/study/manual/teacher-development-skills/08-invite-diligent-learning/033-invite-learners-to-live?lang=eng#title_number2",
      category: "Teaching about Jesus Christ",
      group: "Finding Him in the scriptures",
      moment: ["during"] }
  ],

  // Bonus: the ten task scenarios for test mode. expect is the block we
  // filed the answer under — recorded so a run can be scored later.
  tasks: [
    { id: "T01",
      scenario: "It is Saturday night and you have not opened the manual yet. You want one thing you can do tonight to get yourself ready to teach tomorrow.",
      expect: "017.title_number2" },
    { id: "T02",
      scenario: "You ask the class a question. Nobody answers. You wait. Still nothing. Find something you could try instead.",
      expect: "023.title_number1" },
    { id: "T03",
      scenario: "A teenager asks you a question about the temple and you genuinely do not know the answer. Find advice on what to say.",
      expect: "026.title_number3" },
    { id: "T04",
      scenario: "You teach seven-year-olds and you are losing them ten minutes in. Find something to do with your hands instead of talking.",
      expect: "006.title_number2" },
    { id: "T05",
      scenario: "Last week you invited your class to try something at home. It is Sunday again. Find how to follow up on it.",
      expect: "033.title_number1" },
    { id: "T06",
      scenario: "One boy sits at the back and never says a word, and you think he believes the class would run fine without him. Find something to do about that.",
      expect: "014.title_number3" },
    { id: "T07",
      scenario: "You noticed something good about a girl in your class this week and you want to do something with what you noticed.",
      expect: "015.title_number1" },
    { id: "T08",
      scenario: "Your lesson on honesty is turning into a school lesson. Find how to bring Jesus Christ into it.",
      expect: "004.title_number1" },
    { id: "T09",
      scenario: "A woman in your class says she can never tell whether a feeling is the Spirit or just her own thoughts. Find something that would help her.",
      expect: "020.title_number3" },
    { id: "T10",
      scenario: "You want the first two minutes of your lesson to actually land instead of being announcements. Find something to open with.",
      expect: "027.title_number2" }
  ]
};

